package com.example.aamezencev.handbook.data.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.aamezencev.handbook.data.db.DataHierarchyDb;
import com.example.aamezencev.handbook.data.db.HierarchyElementDb;
import com.example.aamezencev.handbook.data.db.PointerDataDb;
import com.example.aamezencev.handbook.data.db.ThreeDimensionalModelDb;

import com.example.aamezencev.handbook.data.db.DataHierarchyDbDao;
import com.example.aamezencev.handbook.data.db.HierarchyElementDbDao;
import com.example.aamezencev.handbook.data.db.PointerDataDbDao;
import com.example.aamezencev.handbook.data.db.ThreeDimensionalModelDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataHierarchyDbDaoConfig;
    private final DaoConfig hierarchyElementDbDaoConfig;
    private final DaoConfig pointerDataDbDaoConfig;
    private final DaoConfig threeDimensionalModelDbDaoConfig;

    private final DataHierarchyDbDao dataHierarchyDbDao;
    private final HierarchyElementDbDao hierarchyElementDbDao;
    private final PointerDataDbDao pointerDataDbDao;
    private final ThreeDimensionalModelDbDao threeDimensionalModelDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataHierarchyDbDaoConfig = daoConfigMap.get(DataHierarchyDbDao.class).clone();
        dataHierarchyDbDaoConfig.initIdentityScope(type);

        hierarchyElementDbDaoConfig = daoConfigMap.get(HierarchyElementDbDao.class).clone();
        hierarchyElementDbDaoConfig.initIdentityScope(type);

        pointerDataDbDaoConfig = daoConfigMap.get(PointerDataDbDao.class).clone();
        pointerDataDbDaoConfig.initIdentityScope(type);

        threeDimensionalModelDbDaoConfig = daoConfigMap.get(ThreeDimensionalModelDbDao.class).clone();
        threeDimensionalModelDbDaoConfig.initIdentityScope(type);

        dataHierarchyDbDao = new DataHierarchyDbDao(dataHierarchyDbDaoConfig, this);
        hierarchyElementDbDao = new HierarchyElementDbDao(hierarchyElementDbDaoConfig, this);
        pointerDataDbDao = new PointerDataDbDao(pointerDataDbDaoConfig, this);
        threeDimensionalModelDbDao = new ThreeDimensionalModelDbDao(threeDimensionalModelDbDaoConfig, this);

        registerDao(DataHierarchyDb.class, dataHierarchyDbDao);
        registerDao(HierarchyElementDb.class, hierarchyElementDbDao);
        registerDao(PointerDataDb.class, pointerDataDbDao);
        registerDao(ThreeDimensionalModelDb.class, threeDimensionalModelDbDao);
    }
    
    public void clear() {
        dataHierarchyDbDaoConfig.clearIdentityScope();
        hierarchyElementDbDaoConfig.clearIdentityScope();
        pointerDataDbDaoConfig.clearIdentityScope();
        threeDimensionalModelDbDaoConfig.clearIdentityScope();
    }

    public DataHierarchyDbDao getDataHierarchyDbDao() {
        return dataHierarchyDbDao;
    }

    public HierarchyElementDbDao getHierarchyElementDbDao() {
        return hierarchyElementDbDao;
    }

    public PointerDataDbDao getPointerDataDbDao() {
        return pointerDataDbDao;
    }

    public ThreeDimensionalModelDbDao getThreeDimensionalModelDbDao() {
        return threeDimensionalModelDbDao;
    }

}
