package com.example.aamezencev.handbook.data.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "POINTER_HIERARCHY_DB".
*/
public class PointerHierarchyDbDao extends AbstractDao<PointerHierarchyDb, Long> {

    public static final String TABLENAME = "POINTER_HIERARCHY_DB";

    /**
     * Properties of entity PointerHierarchyDb.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property PrimaryKey = new Property(0, Long.class, "primaryKey", true, "_id");
        public final static Property StartIndex = new Property(1, Integer.class, "startIndex", false, "START_INDEX");
        public final static Property FinalIndex = new Property(2, Integer.class, "finalIndex", false, "FINAL_INDEX");
        public final static Property RefDataHierarchyDb = new Property(3, long.class, "refDataHierarchyDb", false, "REF_DATA_HIERARCHY_DB");
        public final static Property RefThreeDimensionalModel = new Property(4, long.class, "refThreeDimensionalModel", false, "REF_THREE_DIMENSIONAL_MODEL");
    }

    private DaoSession daoSession;

    private Query<PointerHierarchyDb> dataHierarchyDb_PointerListQuery;

    public PointerHierarchyDbDao(DaoConfig config) {
        super(config);
    }
    
    public PointerHierarchyDbDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"POINTER_HIERARCHY_DB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: primaryKey
                "\"START_INDEX\" INTEGER," + // 1: startIndex
                "\"FINAL_INDEX\" INTEGER," + // 2: finalIndex
                "\"REF_DATA_HIERARCHY_DB\" INTEGER NOT NULL ," + // 3: refDataHierarchyDb
                "\"REF_THREE_DIMENSIONAL_MODEL\" INTEGER NOT NULL );"); // 4: refThreeDimensionalModel
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"POINTER_HIERARCHY_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PointerHierarchyDb entity) {
        stmt.clearBindings();
 
        Long primaryKey = entity.getPrimaryKey();
        if (primaryKey != null) {
            stmt.bindLong(1, primaryKey);
        }
 
        Integer startIndex = entity.getStartIndex();
        if (startIndex != null) {
            stmt.bindLong(2, startIndex);
        }
 
        Integer finalIndex = entity.getFinalIndex();
        if (finalIndex != null) {
            stmt.bindLong(3, finalIndex);
        }
        stmt.bindLong(4, entity.getRefDataHierarchyDb());
        stmt.bindLong(5, entity.getRefThreeDimensionalModel());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PointerHierarchyDb entity) {
        stmt.clearBindings();
 
        Long primaryKey = entity.getPrimaryKey();
        if (primaryKey != null) {
            stmt.bindLong(1, primaryKey);
        }
 
        Integer startIndex = entity.getStartIndex();
        if (startIndex != null) {
            stmt.bindLong(2, startIndex);
        }
 
        Integer finalIndex = entity.getFinalIndex();
        if (finalIndex != null) {
            stmt.bindLong(3, finalIndex);
        }
        stmt.bindLong(4, entity.getRefDataHierarchyDb());
        stmt.bindLong(5, entity.getRefThreeDimensionalModel());
    }

    @Override
    protected final void attachEntity(PointerHierarchyDb entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PointerHierarchyDb readEntity(Cursor cursor, int offset) {
        PointerHierarchyDb entity = new PointerHierarchyDb( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // primaryKey
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // startIndex
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // finalIndex
            cursor.getLong(offset + 3), // refDataHierarchyDb
            cursor.getLong(offset + 4) // refThreeDimensionalModel
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PointerHierarchyDb entity, int offset) {
        entity.setPrimaryKey(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStartIndex(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setFinalIndex(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setRefDataHierarchyDb(cursor.getLong(offset + 3));
        entity.setRefThreeDimensionalModel(cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PointerHierarchyDb entity, long rowId) {
        entity.setPrimaryKey(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PointerHierarchyDb entity) {
        if(entity != null) {
            return entity.getPrimaryKey();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PointerHierarchyDb entity) {
        return entity.getPrimaryKey() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "pointerList" to-many relationship of DataHierarchyDb. */
    public List<PointerHierarchyDb> _queryDataHierarchyDb_PointerList(long refDataHierarchyDb) {
        synchronized (this) {
            if (dataHierarchyDb_PointerListQuery == null) {
                QueryBuilder<PointerHierarchyDb> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.RefDataHierarchyDb.eq(null));
                dataHierarchyDb_PointerListQuery = queryBuilder.build();
            }
        }
        Query<PointerHierarchyDb> query = dataHierarchyDb_PointerListQuery.forCurrentThread();
        query.setParameter(0, refDataHierarchyDb);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getThreeDimensionalModelDbDao().getAllColumns());
            builder.append(" FROM POINTER_HIERARCHY_DB T");
            builder.append(" LEFT JOIN THREE_DIMENSIONAL_MODEL_DB T0 ON T.\"REF_THREE_DIMENSIONAL_MODEL\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PointerHierarchyDb loadCurrentDeep(Cursor cursor, boolean lock) {
        PointerHierarchyDb entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        ThreeDimensionalModelDb threeDimensionalModelDb = loadCurrentOther(daoSession.getThreeDimensionalModelDbDao(), cursor, offset);
         if(threeDimensionalModelDb != null) {
            entity.setThreeDimensionalModelDb(threeDimensionalModelDb);
        }

        return entity;    
    }

    public PointerHierarchyDb loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PointerHierarchyDb> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PointerHierarchyDb> list = new ArrayList<PointerHierarchyDb>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PointerHierarchyDb> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PointerHierarchyDb> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
